nelmio_api_doc:
    documentation:
        servers:
            - url: http://127.0.0.1:8000
              description: Local development server
        info:
            title: NETEA Interview task
            description: Quick interview application
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/assignment/ # Accepts routes under /assignment
